### ISSUE TITLE
update to  ACMEv2 compatible client

### ISSUE THREAD

**Issue by domi-a** [Alexander-Krause/rpi-docker-letsencrypt-nginx-proxy-companion#1]
Beginning June 1, 2020, Letzencrypt will stop allowing new domains to validate using
the ACMEv1 protocol.

your forked from JrCs/docker-letsencrypt-nginx-proxy-companion, which seems to be alredy using ACMEv2 client.

could you please update too.

...
using your image on rpi-3, best decision ever. thank you for your work

**Comment by Alexander-Krause-Glau** [comment]
Done with 7afd5b5a9586de43cc9705a176fb08bc553daa51. 

Thank you for using this software. Again, all credit goes to Yves Blusseau, Nicolas Duchon, and all the contributors of the original Github repository.
