### ISSUE TITLE
Is it possible to have multiple LETSENCRYPT_HOSTs?

### ISSUE THREAD

**Issue by turbosnute** [Alexander-Krause/rpi-docker-letsencrypt-nginx-proxy-companion#3]
I have a apache2 container that I want to have two domains (example.com and www.example.com). Is it possible to have multiple LETSENCRYPT_HOST (and virtualhosts) defined?

**Comment by shadowhunter1967** [comment]
Same question for me.  What is needed to add a  value to the letsencrypt certificate SAN attribute (Subject Alternative Name)? I would like to add a private FQDN to the SAN attribute so I'm able to use my private internal DNS

**Comment by Alexander-Krause-Glau** [comment]
Hi, since `www` is a subdomain, did you try a comma separated list of domain names, e.g.,
```
"VIRTUAL_HOST=www.domain.com,domain.com"
"LETSENCRYPT_HOST=www.domain.com,domain.com"
```

**Comment by turbosnute** [comment]
> Hi, since `www` is a subdomain, did you try a comma separated list of domain names, e.g.,
> 
> ```
> "VIRTUAL_HOST=www.domain.com,domain.com"
> "LETSENCRYPT_HOST=www.domain.com,domain.com"
> ```

It seem to work! Thanks!
